@startuml JoymonOnline_Context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!include vars.puml
Person(personAlias, "Internet User", USER_DESC)
System(joymononline, "JoymonOnline", "JoymonOnline Website")
System_Ext(blogger,"Blogger","Blogger")
System_Ext(stackOverflow,"StackOverflow","A question answer site")
System_Ext(github,"GitHub","Provides hosting for software development version control using Git")
System_Ext(linkedIn,"Linked In","A professional networking site")
System_Ext(googleDocs,"Google Docs","Hosts, edit and share documents")
Rel(personAlias, joymononline, "Access site", "TCP 443,http,Anonymous")
Rel(joymononline,blogger,"Access blog feed","TCP 443,http(s)")
Rel(joymononline,stackOverflow,"Access profile data to show badge","TCP 443,http(s)")
Rel(joymononline,github,"Access the project details, get whatnew page contents","TCP 443,http(s)")
Rel(joymononline,linkedIn,"Access profile to show profile image","TCP 443,http(s)")
Rel(joymononline,googleDocs,"Preview of resume","TCP 443,http(s)")
@enduml
