@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/joymon/JoymonOnline.In/master/diagrams/vars.puml
'Uncomment the below to work locally
'!include vars.puml

Person(personAlias, "Internet User", USER_DESC)
System_Boundary(joymononline, "JoymonOnline"){
    Container(browser,"WebBrowser","HTML, JavaScript, CSS, AngularJS","Any web browser supporting AngularJS")
    Container(joymonOnlineWebSite, "JoymonOnlineWebSite", "HTML, CSS, JavaScript, Git Pages", "Serves web site. Static files")
    Rel(browser,joymonOnlineWebSite,"Access the website","TCP 443,http(s), Anonymous")
}
System_Ext(blogger,"Blogger",BLOGGER_SYS_DESC)
System_Ext(stackOverflow,"StackOverflow",SO_SYS_DESC)
System_Ext(github,"GitHub",GH_SYS_DESC)
System_Ext(linkedIn,"Linked In",LI_SYS_DESC)
System_Ext(twitter,"Twitter",TWITTER_SYS_DESC)
System_Ext(facebook,"Facebook",FB_SYS_DESC)
System_Ext(youtube,"YouTube",YT_SYS_DESC)
System_Ext(googleDocs,"Google Docs",GD_SYS_DESC)
Rel(browser,blogger,"Access blog feed","TCP 443,http(s)")
Rel(browser,stackOverflow,"Access profile data to show badge","TCP 443,http(s)")
Rel(personAlias, browser, "Access site", "Opens browser and navigate")
Rel(browser,github,"Access the project details, get whatnew page contents","TCP 443,http(s)")
Rel(browser,linkedIn,"Access profile to show profile image","TCP 443,http(s)")
Rel(browser,twitter,"Navigtes","HTML Link")
Rel(browser,facebook,"Navigtes","HTML Link")
Rel(browser,youtube,"Navigtes","HTML Link")
Rel(browser,googleDocs,"Preview of resume","TCP 443,http(s)")
@enduml
